name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set variables
      id: vars
      run: |
        VERSION=${GITHUB_REF/refs\/tags\//}
        URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${VERSION}/assets{?name,label}"
        echo ::set-output name=VERSION::${VERSION}
        echo ::set-output name=URL::${URL}
    - name: Build plugin
      run: |
        xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited) CHILLSCREEN_VERSION=\@\"${VERSION}\"'
        zip -vr ChillScreen.mailbundle.zip ./build/Release/ChillScreen.mailbundle
      env:
        VERSION: ${{ steps.vars.outputs.VERSION }}
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.vars.outputs.URL }}
        asset_path: ./ChillScreen.mailbundle.zip
        asset_name: ChillScreen.mailbundle.zip
        asset_content_type: application/zip
