name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set variables
      id: vars
      run: |
        NAME="ChillScreen.mailbundle"

        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        echo ::set-output name=BUILD_PATH::"./build/Release/${NAME}"
        echo ::set-output name=ARTIFACT::"${NAME}.zip"
    - name: Build plugin
      run: |
        xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited) CHILLSCREEN_VERSION=\@\"${{ steps.vars.outputs.VERSION }}\"'
        zip -vr ${{ steps.vars.outputs.ARTIFACT }} ${{ steps.vars.outputs.BUILD_PATH }}
    - name: Upload plugin
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./${{ steps.vars.outputs.ARTIFACT }}
        asset_name: ${{ steps.vars.outputs.ARTIFACT }}
        tag: ${{ github.ref }}
        overwrite: true
